// <auto-generated />
using EmployeeForm.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeForm.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260206090216_mg2")]
    partial class mg2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeForm.Models.tblcity", b =>
                {
                    b.Property<int>("cityid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cityid"));

                    b.Property<string>("cityname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stateid")
                        .HasColumnType("int");

                    b.HasKey("cityid");

                    b.ToTable("tblcities");

                    b.HasData(
                        new
                        {
                            cityid = 1,
                            cityname = "Ahmedabad",
                            stateid = 1
                        },
                        new
                        {
                            cityid = 2,
                            cityname = "Surat",
                            stateid = 1
                        },
                        new
                        {
                            cityid = 3,
                            cityname = "Mumbai",
                            stateid = 2
                        },
                        new
                        {
                            cityid = 4,
                            cityname = "Pune",
                            stateid = 2
                        },
                        new
                        {
                            cityid = 5,
                            cityname = "Lahore",
                            stateid = 3
                        },
                        new
                        {
                            cityid = 6,
                            cityname = "Multan",
                            stateid = 3
                        },
                        new
                        {
                            cityid = 7,
                            cityname = "Karachi",
                            stateid = 4
                        },
                        new
                        {
                            cityid = 8,
                            cityname = "Hyderabad",
                            stateid = 4
                        });
                });

            modelBuilder.Entity("EmployeeForm.Models.tblcountry", b =>
                {
                    b.Property<int>("countryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("countryid"));

                    b.Property<string>("countryname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("countryid");

                    b.ToTable("tblcountries");

                    b.HasData(
                        new
                        {
                            countryid = 1,
                            countryname = "India"
                        },
                        new
                        {
                            countryid = 2,
                            countryname = "Pakistan"
                        });
                });

            modelBuilder.Entity("EmployeeForm.Models.tblemployee", b =>
                {
                    b.Property<int>("empid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("empid"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<int>("city")
                        .HasColumnType("int");

                    b.Property<int>("country")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<string>("hobbies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("state")
                        .HasColumnType("int");

                    b.HasKey("empid");

                    b.ToTable("tblemployees");
                });

            modelBuilder.Entity("EmployeeForm.Models.tblgender", b =>
                {
                    b.Property<int>("genderid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("genderid"));

                    b.Property<string>("gendername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("genderid");

                    b.ToTable("tblgenders");

                    b.HasData(
                        new
                        {
                            genderid = 1,
                            gendername = "Male"
                        },
                        new
                        {
                            genderid = 2,
                            gendername = "Female"
                        },
                        new
                        {
                            genderid = 3,
                            gendername = "Transgender"
                        });
                });

            modelBuilder.Entity("EmployeeForm.Models.tblhobby", b =>
                {
                    b.Property<int>("hobbyid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hobbyid"));

                    b.Property<string>("hobbyname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("hobbyid");

                    b.ToTable("tblhobbies");

                    b.HasData(
                        new
                        {
                            hobbyid = 1,
                            hobbyname = "Cricket"
                        },
                        new
                        {
                            hobbyid = 2,
                            hobbyname = "Football"
                        },
                        new
                        {
                            hobbyid = 3,
                            hobbyname = "Reading"
                        },
                        new
                        {
                            hobbyid = 4,
                            hobbyname = "Music"
                        },
                        new
                        {
                            hobbyid = 5,
                            hobbyname = "Traveling"
                        },
                        new
                        {
                            hobbyid = 6,
                            hobbyname = "Gaming"
                        },
                        new
                        {
                            hobbyid = 7,
                            hobbyname = "Cooking"
                        },
                        new
                        {
                            hobbyid = 8,
                            hobbyname = "Photography"
                        });
                });

            modelBuilder.Entity("EmployeeForm.Models.tblstate", b =>
                {
                    b.Property<int>("stateid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stateid"));

                    b.Property<int>("countryid")
                        .HasColumnType("int");

                    b.Property<string>("statename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("stateid");

                    b.ToTable("tblstates");

                    b.HasData(
                        new
                        {
                            stateid = 1,
                            countryid = 1,
                            statename = "Gujarat"
                        },
                        new
                        {
                            stateid = 2,
                            countryid = 1,
                            statename = "Maharashtra"
                        },
                        new
                        {
                            stateid = 3,
                            countryid = 2,
                            statename = "Punjab"
                        },
                        new
                        {
                            stateid = 4,
                            countryid = 2,
                            statename = "Sindh"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
